name: Build wheels and release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build_wheels:
    name: ${{ matrix.os }} / ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, "macos-10.15"]
        python: [3.6, 3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Build wheels(MacOS, Windows)
        if: runner.os != 'Linux'
        run: python setup.py bdist_wheel

      - name: Build wheels(Linux)
        if: runner.os == 'Linux'
        run: python setup.py bdist_wheel -p manylinux2010_x86_64"

      - name: Test wheel
        run: |
          python -m pip install tokei --no-index -f dist/
          tokei --help

      - name: Publish a Python distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        run: |
          python -m pip install twine
          twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN}} dist/*
